###
# @name getGoogle
GET https://www.google.com
User-Agent: resterm/0.1

###
# @name createPost
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}


###
# @name authTest
# @auth bearer {{auth.token}}
GET https://httpbin.org/bearer

###
# @global auth.clientSecret demo-secret
# @name oauthDemo
# @auth oauth2 token_url=https://auth.example.com/oauth/token client_id=demo-client client_secret={{auth.clientSecret}} scope="read write"
GET https://httpbin.org/anything
