### Status Check
# @name getStatus
GET {{base.url}}/status/204
User-Agent: resterm/0.1
Accept: application/json

### Create Post
# @name createPost
POST {{base.url}}/anything/posts
Content-Type: application/json
Accept: application/json

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}

### Bearer Auth Example
# @name bearerEcho
# @auth bearer {{auth.token}}
GET {{base.url}}/bearer
Accept: application/json

### OAuth2 Directive
# @name oauthDirectiveDemo
# @description Demonstrates Resterm's built-in @auth oauth2 support with environment-driven parameters.
# @auth oauth2 token_url={{oauth.tokenUrl}} client_id={{oauth.clientId}} client_secret={{oauth.clientSecret}} scope="{{oauth.scope}}" audience={{oauth.audience}} cache_key={{oauth.cacheKey}}
GET {{base.url}}/anything/oauth2-demo
Accept: application/json
